name: .NET

on:
  push:
    branches:  test 

jobs:
  build:
    runs-on: 'windows-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Setup MSBuild path
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Restore NuGet packages
      run: nuget restore
      
    - name: Restore dependencies
      run: dotnet restore
      
    - name: MSBuild
      working-directory: src
      run: Ruilwinkel.csproj 
      
    - name: Test
      run: dotnet test --no-build --verbosity normal

 


      
    
    
    
      
      
      
    
    


        


