name: .NET

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]


jobs:
  build:

    runs-on: windows-latest
    
    steps:
    
    - uses: action/checkout@v2
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
      
    - name: Setup NuGet
      uses: NuGet/setup@v1.0.2
      
    - name: Restore NuGet packages
      run: nuget restore Ruilwinkel.sln
      
    - name: Build the solution
      run: msbuild Ruilwinkel.sln
      
    
    
    
      
      
      
    
    


        


